### ISSUE TITLE
Use StaticArrays for 2x2 matrix functions

### ISSUE THREAD

**Issue by briochemc** [DJ4Earth/DJUICE.jl#3]
Hi @mmorligh and others!

I just stumbled here... I had a quick look for fun and then saw you had your own implementation for 2x2 matrix determinant and inverse. I guess this was to avoid unnecessary loops and checks that generic `det` or `inv` might do? I thought I'd try quick benchmark to see for myself:

```julia
julia> using LinearAlgebra, BenchmarkTools

julia> A = rand(2,2)
2×2 Matrix{Float64}:
 0.664398   0.719668
 0.0551616  0.0282493

julia> function Matrix2x2Determinant(A::Matrix{Float64}) #{{{

               return  A[1,1]*A[2,2]-A[2,1]*A[1,2]

       end#}}}
Matrix2x2Determinant (generic function with 1 method)

julia> function Matrix2x2Invert(A::Matrix{Float64}) #{{{

               #Initialize output
               Ainv = Matrix{Float64}(undef,2,2)

               #Compute determinant
               det = Matrix2x2Determinant(A)
               if(abs(det)<eps(Float64)) error("Determinant smaller than machine epsilon") end

               #Multiplication is faster than divsion, so we multiply by the reciprocal
               det_reciprocal = 1/det

               #compute invert matrix
               Ainv[1,1]=   A[2,2]*det_reciprocal # =  d/det
          Ainv[1,2]= - A[1,2]*det_reciprocal # = -b/det
          Ainv[2,1]= - A[2,1]*det_reciprocal # = -c/det
          Ainv[2,2]=   A[1,1]*det_reciprocal # =  a/det

               return  Ainv

       end#}}}
Matrix2x2Invert (generic function with 1 method)

julia> @btime Matrix2x2Invert($A)
  52.850 ns (1 allocation: 96 bytes)
2×2 Matrix{Float64}:
 -1.34976   34.3858
  2.63563  -31.745

julia> @btime inv($A)
  685.580 ns (4 allocations: 1.30 KiB)
2×2 Matrix{Float64}:
 -1.34976   34.3858
  2.63563  -31.745
```

and indeed it's quite faster (10×) than generic `inv` on this random case. Then I thought what about when Juila knows about the 2×2 size? So I tried with [StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl) and got another 10× speed up:

```julia
julia> using StaticArrays

julia> @btime inv(SMatrix{2,2}($A))
  3.913 ns (0 allocations: 0 bytes)
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 -1.34976   34.3858
  2.63563  -31.745
```

Anyway, I learned something playing around and thought you might want to know about it too, and also in case it can improve your code's performance :) 

Hope you are all well,
Cheers!

**Comment by MathieuMorlighem** [comment]
Hey @briochemc 

So good to hear from you! I hope all is well in Sidney.

This is a great suggestion. The design of dJUICE is largely derived from ISSM (https://issm.jpl.nasa.gov), which is in C++, and so I tried to keep the code as similar as possible. But we should not sacrifice performance of course.

I tested it on my end and converting the 2x2 matrix to a StaticArray + calling `inv` takes an order of magnitude less time than calling `Matrix2x2Invert`, as you noted. I will implement this later this week.

Thanks again for the suggestion, and don't hesitate if you see anything else ;)

Mathieu
